"""Generated documentation: the IP plan and the policy matrix.

Generated from the same inventory as the configs, so the docs can't drift from
what is deployed.
"""

from __future__ import annotations

from .interfaces import Interface
from .ipam import Plan
from .model import Site
from .policy import INTERNET, Flow, intended


def ip_plan(site: Site, plan: Plan, ifaces: dict[str, list[Interface]]) -> str:
    lines = [
        f"# IP plan: {site.name}",
        "",
        "Generated by `python -m netops build` from `inventory/site.yaml`. Do not edit by hand.",
        "",
        f"Site AS {site.asn}, supernet `{site.supernet}`. ISP AS {site.isp_asn}.",
        "",
        "## Segments",
        "",
        "| Segment | VLAN | Subnet | Gateway | Hosts | Usable | Gateway router | Internet |",
        "|---|---:|---|---|---:|---:|---|---|",
    ]
    for s in plan.segments:
        net = "yes" if s.name in site.internet_allowed else "**no**"
        lines.append(
            f"| {s.name} | {s.vlan} | `{s.network}` | `{s.gateway}` | {s.hosts} | {s.usable} | {s.router} | {net} |"
        )
    lines += ["", "## Router loopbacks (router IDs)", "", "| Router | Loopback |", "|---|---|"]
    lines += [f"| {r} | `{ip}/32` |" for r, ip in plan.loopbacks.items()]
    lines += ["", "## Point-to-point links", "", "| Link | Subnet | Addresses |", "|---|---|---|"]
    for link in (*plan.links, plan.isp_link):
        lines.append(f"| {link.a} – {link.b} | `{link.network}` | {link.a} `{link.a_ip}`, {link.b} `{link.b_ip}` |")
    lines += ["", "## Interfaces", "", "| Device | Interface | Address | Connects to |", "|---|---|---|---|"]
    for device, items in ifaces.items():
        for i in items:
            lines.append(f"| {device} | {i.name} | `{i.address}/{i.network.prefixlen}` | {i.peer} |")
    return "\n".join(lines) + "\n"


def policy_matrix(site: Site) -> str:
    """Who may open a connection to whom, as the inventory intends it."""
    names = [s.name for s in site.segments] + [INTERNET]
    ports = sorted({p for r in site.rules for p in r.ports})
    lines = [
        "## Policy matrix (new connections)",
        "",
        "Rows are sources, columns are destinations. Return traffic of an allowed",
        "connection is always allowed (the firewall is stateful).",
        "",
        "| from \\ to | " + " | ".join(names) + " |",
        "|---|" + "---|" * len(names),
    ]
    for src in names:
        cells = []
        for dst in names:
            if src == dst:
                cells.append("—")
                continue
            if intended(site, Flow(src, dst, "icmp")):
                cells.append("all")
                continue
            open_ports = [str(p) for p in ports if intended(site, Flow(src, dst, "tcp", p))]
            if dst == INTERNET and intended(site, Flow(src, dst, "tcp", 443)):
                cells.append("all")
            else:
                cells.append("tcp " + ", ".join(open_ports) if open_ports else "deny")
        lines.append(f"| **{src}** | " + " | ".join(cells) + " |")
    return "\n".join(lines) + "\n"
